config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true
  enum is_finished: { working: false, finished: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if params[:is_finished] == "working"
      session[:is_finished] = "working"
    elsif params[:is_finished] == "finished"
      session[:is_finished] = "finished"
    else
      session[:is_finished] = "all"
    end
    task_where
    @task = Task.new
    @sub_id = 0
  end

  def create
    @task = Task.new(task_params)
    @task.save
    task_where
    @sub_id = 0
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    task_where
    @sub_id = 0
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    task_where
    @sub_id = 0
  end

  private
  def task_where
    if session[:is_finished] == "working"
      @tasks = Task.where(is_finished: "working")
    elsif session[:is_finished] == "finished"
      @tasks = Task.where(is_finished: "finished")
    else
      @tasks = Task.all
    end
  end

  def task_params
    params.require(:task).permit(:content, :is_finished)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MENTA03</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<% tasks.each do |task| %>
  <tr class="todo_<% task.id %>">
    <td><%= @sub_id %></td>
    <td><%= task.content %></td>
    <td class="td_task_status">
      <% if task.is_finished == "working" %>
        <%= button_to "作業中", task_path(task), method: :put, remote: :true, params: { task: {is_finished: "finished"} } %>
      <% else %>
        <%= button_to "完了", task_path(task), method: :put, remote: :true, params: { task: {is_finished: "working"} } %>
      <% end %>
      <%= link_to task_path(task), method: :delete, remote: :true do %>
        <input type="submit" value="削除">
      <% end %>
    </td>
  </tr>
  <% @sub_id += 1 %>
<% end %>

app/views/tasks/create.js.erb
$("#tasksArea").html("<%= j(render 'tasks/task', { tasks: @tasks }) %>")
$("#taskField").html("<%= j(render 'shared/error_messages', { object: @task }) %>")
$("#taskField").val('')

app/views/tasks/destroy.js.erb
$("#tasksArea").html("<%= j(render 'tasks/task', { tasks: @tasks }) %>")

app/views/tasks/index.html.erb
<h1>ToDoリスト</h1>
<%= link_to tasks_path, remote: :true do %>
  <label class="radio_button"><input type="radio" name="taksStatus" id="all" checked class="radio_button">すべて</label>
<% end %>
<%= link_to tasks_path(is_finished: "working"), remote: :true do %>
  <label class="radio_button"><input type="radio" name="taksStatus" id="working" class="radio_button">作業中</label> 
<% end %>
<%= link_to tasks_path(is_finished: "finished"), remote: :true do %>
  <label class="radio_button"><input type="radio" name="taksStatus" id="finished" class="radio_button">完了</label>
<% end %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>コメント</th>
      <th>状態</th>
    </tr>
  </thead>
  <tbody id="tasksArea">
    <%= render "task", tasks: @tasks %>
  </tbody>
</table>

<h2>新規タスクの追加</h2>
  <%= form_with(model: @task) do |f| %>
    <%= f.label :content do %>
      <%= f.text_field :content, id: "taskField", required: :required %>
    <% end %>
    <%= f.submit "追加"%>
  <% end %>

app/views/tasks/index.js.erb
$("#tasksArea").html("<%= j(render 'tasks/task', { tasks: @tasks }) %>")
$(".radio_button").prop('checked', false);
<% if params[:is_finished] == "working" %>
  $("#working").prop('checked', true);
<% elsif params[:is_finished] == "finished" %>
  $("#finished").prop('checked', true);
<% else %>
  $("#all").prop('checked', true);
<% end %>

app/views/tasks/update.js.erb
$("#tasksArea").html("<%= j(render 'tasks/task', { tasks: @tasks }) %>")